export const browserCoreExamples = [
  "cdog browser status",
  "cdog browser start",
  "cdog browser stop",
  "cdog browser tabs",
  "cdog browser open https://example.com",
  "cdog browser focus abcd1234",
  "cdog browser close abcd1234",
  "cdog browser screenshot",
  "cdog browser screenshot --full-page",
  "cdog browser screenshot --ref 12",
  "cdog browser snapshot",
  "cdog browser snapshot --format aria --limit 200",
  "cdog browser snapshot --efficient",
  "cdog browser snapshot --labels",
];

export const browserActionExamples = [
  "cdog browser navigate https://example.com",
  "cdog browser resize 1280 720",
  "cdog browser click 12 --double",
  'cdog browser type 23 "hello" --submit',
  "cdog browser press Enter",
  "cdog browser hover 44",
  "cdog browser drag 10 11",
  "cdog browser select 9 OptionA OptionB",
  "cdog browser upload /tmp/openclaw/uploads/file.pdf",
  'cdog browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "cdog browser dialog --accept",
  'cdog browser wait --text "Done"',
  "cdog browser evaluate --fn '(el) => el.textContent' --ref 7",
  "cdog browser console --level error",
  "cdog browser pdf",
];